const LOADING = 'LOADING';
const IS_STARTUP = 'IS_STARTUP';
const CHANGE_NAME = 'CHANGE_NAME';
const CHANGE_PHONE = 'CHANGE_PHONE';
const CHANGE_EMAIL = 'CHANGE_EMAIL';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
const USER_SIGN_IN = 'USER_SIGN_IN';
export {
  LOADING,
  CHANGE_NAME,
  CHANGE_PHONE,
  CHANGE_EMAIL,
  CHANGE_PASSWORD,
  USER_SIGN_IN,
  IS_STARTUP,
};
